const PUMPSWAP_POOL = "pool";
const PUMPSWAP_GLOBAL_CONFIG = "global_config";
const PUMPSWAP_EVENT_AUTH = "__event_authority";

const PROTOCOL_FEE_RATE = 0.0025;
const CREATOR_FEE_RATE = 0.0005;

export {
    PUMPSWAP_GLOBAL_CONFIG,
    PUMPSWAP_POOL,
    PUMPSWAP_EVENT_AUTH,
    PROTOCOL_FEE_RATE,
    CREATOR_FEE_RATE
}